server:
  port: 8030
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      default-url: http://localhost:8761/eureka/
zuul:
  routes:
    provider: /p/**
    consumer: /c/**